#Server configuration
server:
  port: 8086
  context-path: /api

### DATABASE ###
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
### JPA / HIBERNATE ###
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ebanking?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
transactions:
  rate: 0.02
  vip-rate: 0.01
api:
  API_KEY: ${C4QZKYMV1AKQCWH6}